NAME = OpenGL

SRCS =	Application.cpp \
		Dependencies/GLFW/lib-macos/libglfw3.a \

CC = clang

#FLAGS = -Wall -Werror -Wextra -I ./inc

#OBJ = $(SRCS:.c=.o)

all: $(NAME)

#$(NAME): $(OBJ)
#	make -C libft
#	make -C miniLibX
#	swiftc -o $(NAME) $(FLAGS)
#	echo "Fdf done"

#clean:
#	make clean -C libft
#	rm -f $(OBJ)

#fclean: clean
#	rm -f $(NAME)

#re: fclean all

$(NAME):
	CC $(NAME) $(SRCS) -m32

#clang Application.cpp Dependencies/GLFW/lib-macos/libglfw3.a -m32